/**
 * tool-demo-script — Generate runnable demo scripts from a CLI repo,
 * then verify the commands still work.
 *
 * Library API: generate(repoPath, options) => DemoBundle
 * Library API: verify(demoPath, repoPath, options) => VerificationReport
 */
const path = require('path');
const fs = require('fs');
const { detectEntryPoint } = require('./detector');
const { generateDemoScript, generateNarration, generateConfidenceReport } = require('./generator');
const { runSmoke } = require('./smoke');

/**
 * Generate demo materials for a CLI repo.
 * @param {string} repoPath - path to the repo
 * @param {object} options
 * @returns {object} { scriptMarkdown, narration, confidence, fixtureNotes }
 */
function generate(repoPath, options = {}) {
  const absPath = path.resolve(repoPath);
  const entry = detectEntryPoint(absPath);
  const demo = generateDemoScript(absPath, entry, options);
  const narration = generateNarration(demo);
  const confidence = generateConfidenceReport(absPath, entry, demo);

  return { scriptMarkdown: demo, narration, confidence, entryPoint: entry };
}

/**
 * Verify a demo script still works against the repo.
 * @param {string} demoPath - path to a demo markdown file generated by this tool
 * @param {string} repoPath - path to the repo
 * @returns {object} { passed, failed, skipped, details }
 */
async function verify(demoPath, repoPath, options = {}) {
  const absDemo = path.resolve(demoPath);
  const absRepo = path.resolve(repoPath);
  const demoContent = fs.readFileSync(absDemo, 'utf8');
  return await runSmoke(absRepo, demoContent, options);
}

module.exports = { generate, verify };
